// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  experience_section: dynamic(() => import("./ExperienceSection")),
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  intro_section: dynamic(() => import("./IntroSection")),
  projects_section: dynamic(() => import("./ProjectsSection")),
};
